In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import torch


In [2]:
def f(x,y) :
    return x**2 -y**2

In [7]:
x=torch.tensor(0.).requires_grad_()
y=torch.tensor(0.).requires_grad_()

In [9]:
z=f(x,y)
z

tensor(0., grad_fn=<SubBackward0>)

In [10]:
z.backward()

In [11]:
x.grad

tensor(0.)

In [12]:
y.grad

tensor(-0.)

In [15]:
def cl(r,l):
    return math.pi*r**2*l

In [17]:
r=torch.tensor(3.).requires_grad_()
l=torch.tensor(5.).requires_grad_()

In [18]:
volume =cl(r,l)
volume


tensor(141.3717, grad_fn=<MulBackward0>)

In [19]:
volume.backward()

In [ ]:
l.grad

tensor(28.2743)

In [22]:
v=math.pi*r**2
v

tensor(28.2743, grad_fn=<MulBackward0>)

In [28]:
import tensorflow as tf

In [61]:
def f(x,y) :
    return x**2 -y**2

In [67]:
x= tf.constant(0)
y= tf.constant(0)

In [68]:
with tf.GradientTape() as tape :
    z=f(x,y)


In [69]:
dz_dx, dz_dy = tape.gradient(z, [x, y])


In [1]:
print("z =", z.numpy())



NameError: name 'z' is not defined

In [4]:
x=np.array([[0,1,2],[1,7,8],[2,8,9]])

In [7]:
x.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [6]:
x.T==x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
print("oekoe")

oekoe


In [2]:
a=np.array([[-1,2],[3,-2],[5,7]])
a

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [4]:
np.linalg.norm(a, 'fro')

np.float64(9.591663046625438)

In [5]:
a.T

array([[-1,  3,  5],
       [ 2, -2,  7]])

In [6]:
A=np.dot(a,a.T)
A

array([[ 5, -7,  9],
       [-7, 13,  1],
       [ 9,  1, 74]])

In [7]:
np.trace(A)


np.int64(92)

In [8]:
np.sqrt(np.trace(A))

np.float64(9.591663046625438)